version: '3'

services:
  tests:
    image: unittests
    build:
      context: .
      dockerfile: src/tests/unittests/Dockerfile
    entrypoint: dotnet test
    depends_on:
      - dynamodb

  dynamodb:
    image: cnadiminti/dynamodb-local
    ports: 
      - "8000:8000"

  dynamodb-admin:
    image: boogak/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - "DYNAMO_ENDPOINT=dynamodb:8000"
    depends_on:
      - dynamodb